export const Languages = {
  navbar: {
    register: {
      eng: "Register",
      vn: "Đăng ký",
      cn: "登记",
      kr: "등록하다",
      jp: "登録する",
    },
    login: {
      eng: "Log in",
      vn: "Đăng nhập",
      cn: "登录",
      kr: "로그인",
      jp: "ログイン",
    },
    profile: {
      eng: "Profile",
      vn: "Hồ sơ",
      cn: "轮廓",
      kr: "프로필",
      jp: "プロフィール",
    },
    changePw: {
      eng: "Change password",
      vn: "Đổi mật khẩu",
      cn: "更改密码",
      kr: "비밀번호 변경",
      jp: "パスワードを変更する",
    },
    logout: {
      eng: "Log out",
      vn: "Đăng xuất",
      cn: "登出",
      kr: "로그 아웃",
      jp: "ログアウト",
    },
  },
  header: {
    stay: {
      eng: 'Stays',
      vn: 'Đặt phòng',
      cn: '住宿',
      kr: '숙박',
      jp: '宿泊',
    },
    restaurant: {
      eng: 'Restaurants',
      vn: 'Nhà hàng',
      cn: '餐厅',
      kr: '레스토랑',
      jp: 'レストラン',
    },
    carRental: {
      eng: 'Car rentals',
      vn: 'Thuê xe',
      cn: '汽车租赁',
      kr: '렌터카',
      jp: 'カーレンタル',
    },
    gym: {
      eng: 'Gym fitness',
      vn: 'Gym - thể hình',
      cn: '健身房健身',
      kr: '체육관 피트니스',
      jp: 'ジムフィットネス',
    },
    pool: {
      eng: 'Pool',
      vn: 'Hồ bơi',
      cn: '水池',
      kr: '수영장',
      jp: 'プール',
    },
    title: {
      eng: "A lifetime of discounts? It's Genius.",
      vn: "Giảm giá trọn đời? Cơ hội đang chờ bạn.",
      cn: "终身折扣？这是天才。",
      kr: "평생 할인? 천재입니다.",
      jp: "生涯割引？天才だよ。",
    },
    desc: {
      eng: 'Get rewarded for your travels – unlock instant savings of 10% or more with a free account',
      vn: 'Hãy tận hưởng chuyến đi của bạn - mở khóa khoản tiết kiệm tức thì từ 10% trở lên bằng tài khoản miễn phí',
      cn: '获得旅行奖励 – 使用免费帐户即时节省 10% 或更多',
      kr: '여행에 대한 보상을 받으세요 – 무료 계정으로 즉시 10% 이상의 할인을 받으세요.',
      jp: '旅行の特典を獲得 – 無料アカウントで 10% 以上の即時割引を利用しましょう',
    },
    startBtn: {
      eng: 'Get Started !',
      vn: 'Bắt đầu !',
      cn: '开始吧 ！',
      kr: '시작하다 !',
      jp: '始めましょう！',
    },
    adminBtn: {
      eng: 'Admin page',
      vn: 'Trang quản trị',
      cn: '管理页面',
      kr: '관리자 페이지',
      jp: '管理者ページ',
    },
  },
  home: {
    overview: {
      eng: "Overview about The K",
      vn: "Tổng quan về The K",
      cn: "关于 The K",
      kr: "The K 개요",
      jp: "The Kについての概要",
    },
    services: {
      eng: "Our services",
      vn: "Những dịch vụ của chúng tôi",
      cn: "我们的服务",
      kr: "우리의 서비스",
      jp: "当社のサービス",
    },
    departments: {
      eng: "Our departments",
      vn: "Các chi nhánh của chúng tôi",
      cn: "我们的部门",
      kr: "우리 부서",
      jp: "私たちの部門",
    },
  },
  user: {
    email: {
      eng: "Email",
      vn: "Email",
      cn: "电子邮件",
      kr: "이메일",
      jp: "Eメール",
    },
    phone: {
      eng: "Phone number",
      vn: "Số điện thoại",
      cn: "电话号码",
      kr: "전화 번호",
      jp: "電話番号",
    },
  },
  hotel: {
    department: {
      eng: 'Department',
      vn: 'Chi nhánh',
      cn: '部门',
      kr: '부서',
      jp: '部門',
    },
    hotelDesc: {
      eng: 'The K is a lovely hotel, in the heart of HCMC, within the triangle formed by the bustling pedestrian shopping street Vaci utca, the fascinating Central Market Hall, and the Liberty Bridge. In addition to excellent transport links at the meeting point of the main metro line and tram line, our hotel is surrounded by the city centre’s elegant shops, cafés, restaurants, bars, the famous Gellert Thermal Spa, Szabadsag hid and other tourist sights just a few steps from the left bank of the Danube. Recently, our whole hotel has undergone a complete renovation.',
      vn: 'The K là một khách sạn xinh xắn, nằm ở trung tâm TP.HCM, trong tam giác được hình thành bởi phố mua sắm dành cho người đi bộ nhộn nhịp Vaci utca, Hội trường Chợ Trung tâm hấp dẫn và Cầu Tự Do. Ngoài các kết nối giao thông tuyệt vời tại điểm gặp nhau của tuyến tàu điện ngầm và tuyến xe điện chính, khách sạn của chúng tôi còn được bao quanh bởi các cửa hàng, quán cà phê, nhà hàng, quán bar trang nhã ở trung tâm thành phố, Gellert Thermal Spa nổi tiếng, Szabadsag hid và các điểm tham quan du lịch khác chỉ cách đó một quãng ngắn. vài bước từ bờ trái sông Danube. Gần đây, toàn bộ khách sạn của chúng tôi đã được tân trang lại hoàn toàn.',
      cn: 'K 酒店是一家可爱的酒店，位于胡志明市的中心地带，位于繁华的步行购物街 Vaci utca、迷人的中央市场大厅和自由桥形成的三角形内。 除了主要地铁线和电车线交汇点的便利交通之外，我们酒店周围还有市中心优雅的商店、咖啡馆、餐厅、酒吧、著名的盖勒特温泉、Szabadsag hid 和其他旅游景点，距酒店仅几步之遥。 距多瑙河左岸仅几步之遥。 最近，我们整个酒店进行了全面翻修。',
      kr: 'The K는 번화한 보행자 쇼핑 거리인 Vaci utca, 매혹적인 중앙 시장 홀 및 리버티 브리지로 형성된 삼각형 내에 있는 호치민 중심부에 위치한 아름다운 호텔입니다. 주요 지하철 노선과 트램 노선의 만남의 장소에 있는 훌륭한 교통 연결 외에도 저희 호텔은 도심의 우아한 상점, 카페, 레스토랑, 바, 유명한 겔레르트 온천 스파, Szabadsag 숨은 명소 및 기타 관광 명소로 둘러싸여 있습니다. 다뉴브 강의 왼쪽 강둑에서 몇 걸음 떨어져 있습니다. 최근 호텔 전체가 전면적인 개조 공사를 거쳤습니다.',
      jp: 'The K は、ホーチミン市の中心部にある素敵なホテルです。賑やかな歩行者専用ショッピング街ヴァーツィ通り、魅力的な中央市場ホール、自由の橋によって形成される三角形の中にあります。 主要な地下鉄路線とトラム路線の合流点で交通機関の接続が優れていることに加え、当ホテルは市内中心部のエレガントなショップ、カフェ、レストラン、バー、有名なゲッレールト温泉、シャバザグ隠れ家、その他の観光名所に囲まれています。 ドナウ川の左岸から数歩のところにあります。 最近、ホテル全体が全面改装されました。',
    },
    hotelNote: {
      eng: "You can cancel later, so lock in this great price today!",
      vn: "Bạn có thể hủy sau, vì vậy hãy chốt mức giá tuyệt vời này ngay hôm nay!",
      cn: "您可以稍后取消，所以今天就锁定这个超值价格！",
      kr: "나중에 취소할 수 있으니 오늘 이 놀라운 가격을 확보하세요!",
      jp: "後でキャンセルできるので、今すぐこのお得な価格を確保してください!",
    },
    hotelTax: {
      eng: "You can cancel later, so lock in this great price today!",
      vn: "Bao gồm thuế và phí",
      cn: "包括税费",
      kr: "세금 및 수수료 포함",
      jp: "税金と手数料が含まれます",
    },
  },
  reservation: {
    title: {
      eng: "Reservation",
      vn: "Đơn phòng",
      cn: "预订",
      kr: "예약",
      jp: "予約",
    },
    info: {
      eng: 'Reservation Information',
      vn: 'Thông tin đơn phòng',
      cn: '预约信息',
      kr: '예약정보',
      jp: '予約情報',
    },
    id: {
      eng: 'Reservation ID',
      vn: 'Mã đơn phòng ID',
      cn: '预订ID',
      kr: '예약번호',
      jp: '予約ID',
    },
    adult: {
      eng: 'Adult',
      vn: 'Người lớn',
      cn: '成人',
      kr: '성인',
      jp: 'アダルト',
    },
    children: {
      eng: 'Children',
      vn: 'Trẻ em',
      cn: '孩子们',
      kr: '어린이들',
      jp: '子供たち',
    },
    singleRoom: {
      eng: 'Single room',
      vn: 'Phòng đơn',
      cn: '单人房',
      kr: '싱글룸',
      jp: 'シングルルーム',
    },
    doubleRoom: {
      eng: 'Double room',
      vn: 'Phòng đôi',
      cn: '双人间',
      kr: '더블룸',
      jp: 'ダブルルーム',
    },
    bookingType: {
      eng: "Type of Booking",
      vn: "Loại hình đơn phòng",
      cn: "预订类型",
      kr: "예약 유형",
      jp: "予約の種類",
    },
    avaiRoom: {
      eng: 'See available rooms',
      vn: 'Hiển thị phòng khả dụng',
      cn: '查看可用房间',
      kr: '예약 가능한 방 보기',
      jp: '空室のある部屋を見る',
    },
    checkIn: {
      eng: "Check In",
      vn: "Nhận phòng",
      cn: "报到",
      kr: "체크인",
      jp: "チェックイン",
    },
    checkOut: {
      eng: "Check Out",
      vn: "Trả phòng",
      cn: "查看",
      kr: "확인해 보세요",
      jp: "チェックアウト",
    },
    checkInDate: {
      eng: "Check In Date",
      vn: "Ngày nhận phòng",
      cn: "离开日期",
      kr: "체크인 날짜",
      jp: "チェックインする日",
    },
    checkOutDate: {
      eng: "Check Out Date",
      vn: "Ngày trả phòng",
      cn: "入住日期",
      kr: "체크아웃 날짜",
      jp: "チェックアウト日",
    },
    customerName: {
      eng: "Customer Name",
      vn: "Tên khách hành",
      cn: "顾客姓名",
      kr: "고객 이름",
      jp: "顧客名",
    },
    room: {
      eng: "Room",
      vn: "Phòng",
      cn: "房间",
      kr: "방",
      jp: "部屋",
    },
    roomNumber: {
      eng: "Room Number",
      vn: "Số phòng",
      cn: "房间号",
      kr: "방번호",
      jp: "部屋番号",
    },
    todayAct: {
      eng: "Today's Activities",
      vn: "Hoạt động hôm nay",
      cn: "今天的活动",
      kr: "오늘의 활동",
      jp: "今日の活動",
    },
    reservationList: {
      eng: "Reservation List",
      vn: "Danh sách đơn phòng",
      cn: "列表预订",
      kr: "목록 예약",
      jp: "リスト予約",
    },
    arrivals: {
      eng: "Arrivals",
      vn: "Nhận phòng",
      cn: "到达",
      kr: "도착",
      jp: "到着",
    },
    departures: {
      eng: "Departures",
      vn: "Trả phòng",
      cn: "班次",
      kr: "출발",
      jp: "出発",
    },
    stayOver: {
      eng: "Stay over",
      vn: "Ở lại",
      cn: "住宿",
      kr: "숙박",
      jp: "宿泊",
    },
    reserve: {
      eng: "Book or reserve your spot now",
      vn: "Đặt hoặc đặt chỗ ngay bây giờ",
      cn: "立即预订或预留位置",
      kr: "지금 예약하거나 자리를 예약하세요",
      jp: "今すぐ予約または予約してください",
    },
    day: {
      eng: "Day",
      vn: "Ngày",
      cn: "天",
      kr: "일",
      jp: "日",
    },
  },
  service: {
    relaxSpace: {
      eng: "Relax Space",
      vn: "Không gian giải trí",
      cn: "放松空间",
      kr: "릴렉스 스페이스",
      jp: "リラックススペース",
    },
    partyOrg: {
      eng: "Party Organization",
      vn: "Tổ chức sự kiện",
      cn: "党组织",
      kr: "파티 조직",
      jp: "党組織",
    },
    rentCars: {
      eng: "Rent Cars",
      vn: "Thuê xe",
      cn: "租车",
      kr: "자동차 렌트",
      jp: "レンタカー",
    },
    gym: {
      eng: "Gym & Fitness",
      vn: "Gym & Fitness",
      cn: "健身房和健身",
      kr: "체육관 및 피트니스",
      jp: "ジム＆フィットネス",
    },
    pool: {
      eng: "Swimming Pool",
      vn: "Hồ bơi",
      cn: "游泳池",
      kr: "수영장",
      jp: "スイミングプール",
    },
    billiards: {
      eng: "Billiards",
      vn: "Billiards",
      cn: "台球",
      kr: "당구",
      jp: "ビリヤード",
    },
  },
  msg: {
    payMethod: {
      eng: "How would you like to pay",
      vn: "Chọn phương thức thanh toán",
      cn: "你想怎么支付",
      kr: "어떻게 지불 하시겠습니까",
      jp: "お支払い方法をご希望ですか",
    }
  },
  other: {
    back: {
      eng: "Back",
      vn: "Trở lại",
      cn: "后退",
      kr: "뒤쪽에",
      jp: "戻る",
    },
    view: {
      eng: "View",
      vn: "Xem",
      cn: "看法",
      kr: "보다",
      jp: "ビュー",
    },
    continue: {
      eng: "Continue",
      vn: "Tiếp tục",
      cn: "继续",
      kr: "계속하다",
      jp: "続く",
    },
    cancel: {
      eng: "Cancel",
      vn: "Hủy",
      cn: "取消",
      kr: "취소",
      jp: "キャンセル",
    },
    detail: {
      eng: "See Details",
      vn: "Chi tiết",
      cn: "查看具体信息",
      kr: "자세히보다",
      jp: "詳細を見る",
    },
    freeCancel: {
      eng: "Free cancellation",
      vn: "Miễn phí hủy đơn",
      cn: "免费取消",
      kr: "무료 취소",
      jp: "無料キャンセル",
    },
    search: {
      eng: 'Search',
      vn: 'Tìm kiếm',
      cn: '水池',
      kr: '수영장',
      jp: 'プール',
    },
    options: {
      eng: 'Options',
      vn: 'Tùy chọn',
      cn: '选项',
      kr: '옵션',
      jp: 'オプション',
    },
    cmt: {
      eng: "Comment",
      vn: "Bình luận",
      cn: "评论",
      kr: "논평",
      jp: "コメント",
    },
    cmtType: {
      eng: "Type your comment",
      vn: "Nhập bình luận của bạn",
      cn: "输入您的评论",
      kr: "댓글을 입력하세요",
      jp: "コメントを入力してください",
    },
    tax: {
      eng: "Tax",
      vn: "Thuế",
      cn: "税",
      kr: "세",
      jp: "税",
    },
    expense: {
      eng: "Expense",
      vn: "Chi phí",
      cn: "费用",
      kr: "비용",
      jp: "費用",
    },
    total: {
      eng: "Total",
      vn: "Tổng cộng",
      cn: "全部",
      kr: "총",
      jp: "合計",
    },
    bookingSum: {
      eng: "Booking Summary",
      vn: "Tóm tắt đặt phòng",
      cn: "预订摘要",
      kr: "예약 요약",
      jp: "予約概要",
    },
    empty: {
      eng: "",
      vn: "",
      cn: "",
      kr: "",
      jp: "",
    },
  },
}